services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - C:/pdv/keycloak:/var/lib/mysql
      - ./init-schema.sql:/docker-entrypoint-initdb.d/init-schema.sql
    ports:
      - 3307:3306
    networks:
      - keycloak_network

  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      KC_DB: mysql
      KC_DB_URL_HOST: mysql
      KC_DB_URL_PORT: 3306
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
    ports:
      - 8081:8080
    depends_on:
      - mysql
    networks:
      - keycloak_network

networks:
  keycloak_network:
    driver: bridge
